tweet_analysis/urls.py
from django.contrib import admin
from django.urls import path,include
from tweetapp import views



urlpatterns = [
    path("",include("tweetapp.urls")),
    path('admin/', admin.site.urls),
]

tweetapp/urls.py
from django.urls import path, include
from . import views

app_name = "tweetapp"

urlpatterns = [
    path('', views.index, name='index'),
    path('get_wordcloud_img/', views.get_wordcloud_img, name="get_wordcloud_img"),
    path(r"tw_request/<path:imgur_url>/", views.show_picture,
         name="tw_request")
]

tweetapp/models.py
from django.db import models

# Create your models here.

tweetapp/views.py
from django.shortcuts import render
import io
import urllib, base64
import MeCab
import matplotlib.pyplot as plt
from wordcloud import WordCloud
# from tweetapp.bq import UpDownLoad, ipaexg_PATH
import requests
import json
from tweetapp.bq import UpDownLoad
import pandas as pd


# Create your views here.

def index(request):
    return render(request, "tweetapp/index.html")


def get_wordcloud_img(request):
    tw_id = request.POST["tweet_id"]
    url = f"https://us-central1-instant-icon-250708.cloudfunctions.net/tw_analysis?message={tw_id}"
    res = requests.get(url)
    # res = "https://storage.cloud.google.com/mytweet_840/wordcloud_img/wordcloud.png?hl=ja"
    gcs_img, imgur_url = json.loads(res.text.replace("'", '"'))

    # image_64 = "https://storage.cloud.google.com/mytweet_840/wordcloud_img/wordcloud.png?hl=ja"
    # query =
    new_tw_id = f"@{tw_id}"

    return render(request, "tweetapp/index.html", {"gcs_img": gcs_img, "new_tw_id": new_tw_id, "imgur_url": imgur_url})


def show_picture(request, imgur_url):
    return render(request, "tweetapp/index2.html", {"imgur_url": imgur_url})

templates/tweetapp/index.html
<html>
<head>
</head>
<body>
<h1>ツイートを一枚の画像にします</h1>
<h3>表示例:河野大臣(@konotarogomame)の場合</h3>
    <img src="https://storage.cloud.google.com/my_word_cloud3485/2/11/wordcloud_konotarogomame_2020-02-11_21%3A40%3A57.png?hl=ja"
         width="300px" height="300px">
<p>
    Twitter ID(@除く)を入力して下さい
<p>
<form action="{% url  'tweetapp:get_wordcloud_img'  %}" method="post">
    <input name='tweet_id' value="AbeShinzo">
    {%csrf_token%}
    <button type="submit">ツイートを分析</button>
</form>
{% if gcs_img %}
<h3>↓Twitterで画像をシェアしよう！</h3>
<div class="twitter" width="1000px" height="1000px">
    <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-show-count="false"
       data-text="{{new_tw_id}}さんのツイートを分析しました！"
       data-url="https://tactile-wave-267212.appspot.com/tw_request/{{ imgur_url }}" data-lang=ja">Tweet</a>
    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

</div>
<img src="{{ gcs_img }}" width="1000px" height="1000px">


{% endif %}

</body>
</html>
<hr>

templates/tweetapp/index2.html
<html>
<head>
    <meta name="twitter:card" content="summary_large_image"/>
    <meta name="twitter:url" content="https://tactile-wave-267212.appspot.com/"/>
    <meta name="twitter:title" content="ツイート分析アプリです"/>
    <meta name="twitter:description" content="pythonのwordcloudを使ってツイートを分析"/>
    <meta name="twitter:image:src" content="{{ imgur_url }}"/>
</head>

</html>